Add IN clause param interpolation
zio/zio-jdbc pull request #126
Opened 2023-04-27 17:21 UTC by dvivchar

Adds `IN` clause param interpolation.

```scala
val seq = Seq(1, 2, 3)
sql"select name, age from users where id in ($seq)"
```

equals to `Sql(select name, age from users where id in (?,?,?), 1, 2, 3)`

/claim #104

2023-04-27 17:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio-jdbc?pullRequest=126) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio-jdbc?pullRequest=126) before we can accept your contribution.<br/><hr/>**danylo-lohika** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio-jdbc?pullRequest=126) it.</sub>

2023-04-27 17:23 UTC, dvivchar commented
@jdegoes is there any other way to receive bounties? Unfortunately Algora do not work for Ukrainians.

2023-04-27 17:41 UTC, jdegoes commented
That's a big problem, I will chat with their team!

2023-04-27 19:40 UTC, zcesur commented
hey @dvivchar this is Zaf, one of the founders at Algora. Our sincere apologies for the inconvenience here. I understand the  bounty bot comment note "📝 Before proceeding, please make sure you can [receive payouts](https://docs.algora.io/bounties/payments#country-support) in your country" is easy to miss, will fix that.

however, **we do have alternative payment methods** in place and we'll make sure you receive your reward promptly. since you didn't register on Algora and we don't know your email, could you kindly email us at zafer@algora.io and we'll get this sorted asap. thank you for your contribution and collaboration!

2023-04-28 08:52 UTC, dvivchar commented
hey @zcesur thank you for a quick response, I'm having mail conversation with ioannis@algora.io.

2023-05-05 08:04 UTC, jdegoes commented on core/src/main/scala/zio/jdbc/Sql.scala
> +    implicit def sqlIterableSetter[A](implicit setter: Setter[A]): Setter[Seq[A]] =
I think due to contravariant type classes being broken in Scala 2.x, the invariance means that we need to have concrete classes:

```scala
Setter[Chunk[A]]
Setter[List[A]]
Setter[Vector[A]]
Setter[Set[A]]
Setter[Array[A]]
```

Probably those types are enough.

2023-05-05 08:05 UTC, jdegoes requested changes
Looks good, just one small tweak and then good to merge!

2023-05-05 17:00 UTC, dvivchar commented
@jdegoes refactored to concrete collection types, ready to be reviewed again

2023-05-06 16:31 UTC, jdegoes commented
@dvivchar Can you fix merge conflicts, then I will merge? Thanks for your work on this!

2023-05-08 08:32 UTC, dvivchar commented
> @dvivchar Can you fix merge conflicts, then I will merge? Thanks for your work on this!

resolved!

2023-05-08 20:47 UTC, jdegoes commented
@dvivchar Sorry, another commit made it in, looks like one more conflict. Hopefully last one!

2023-05-10 06:56 UTC, dvivchar commented
@jdegoes resolved!

2023-05-12 08:54 UTC, dvivchar commented
unfortunately it's failing with 
```
[error] ## Exception when compiling 2 sources to /home/runner/work/zio-jdbc/zio-jdbc/core/target/scala-2.12/test-classes
[error] java.lang.NullPointerException
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateMatch(MatchTranslation.scala:214)
[error] scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateMatch$(MatchTranslation.scala:194)
```
I guess it's not related to changes in this PR...

2023-05-12 08:57 UTC, adamgfraser commented
@dvivchar All tests are passing on `main` so it does appear to be related to this PR. That looks like a crash in the Scala compiler which unfortunately means there is a compilation error but you are not getting a helpful error message. I would try compiling that version and retrace my steps to the last time it did compile on Scala 2.12 to diagnose.

2023-05-12 11:38 UTC, dvivchar commented
@adamgfraser you are right,
issue was with `Chunk.from(seq)`. Not sure why but compiler crashes on it, while `Chunk.apply` works ok.

2023-05-12 11:59 UTC, adamgfraser commented
@dvivchar `from` was added in the Scala 2.13 collections redesign so doesn't exist in Scala 2.12.

2023-05-12 11:59 UTC, adamgfraser approved these changes

2023-05-13 08:35 UTC, dvivchar commented
@jdegoes could you please approve?

2023-05-13 12:10 UTC, merged