handle connection.isValid thrown exceptions
zio/zio-jdbc pull request #149
Opened 2023-06-30 16:27 UTC by oridag

This fixes an issue where when `isValid` throws, the connection is not invalidated

2023-10-30 17:48 UTC, adamgfraser approved these changes

2023-10-30 17:50 UTC, adamgfraser requested changes
This will silently ignore the error.

2023-11-06 13:54 UTC, oridag commented
@adamgfraser added logging of error. Wasn't sure what log level to use, went with warning. WDYT?

2023-11-06 15:03 UTC, adamgfraser commented
@oridag I think we need to fail with the error, not log it.

2023-11-06 15:09 UTC, oridag commented
@adamgfraser why do you think that? the point of this call is to discard bad connections from the pool, so errors here are actually an expected path

2023-11-06 15:11 UTC, adamgfraser commented
@oridag I think we expect connections to potentially be invalid, not to get errors when determining whether they are valid.

2023-11-06 15:14 UTC, oridag commented
@adamgfraser ok, fail enough. So moving the logging/ignoring to the isValid flow and make it a `UIO[Boolean]` makes sense?

2023-11-06 15:32 UTC, oridag commented
@adamgfraser maybe I'm not being realistic, but potentially, the connection could be valid when the transaction commits, and only become invalid when the finalizer runs, in which case, as a user, I don't want my workflow to fail.

2023-11-06 15:34 UTC, adamgfraser commented
@oridag The issue is not whether the transaction is valid but whether that an error occurs in determining whether the transactions is valid. If so that is an error we should propagate.

2023-11-06 15:42 UTC, oridag commented
@adamgfraser consider the following scenario:
1. A DB INSERT statement runs and succeeds
2. Just after that, the TCP connection is broken
3. The finalizer runs and results in an error

In that scenario, you don't want the user code to fail, right? you want it to succeed but invalidate the connection so it wont be used again.

2023-11-06 15:45 UTC, adamgfraser commented
@oridag I think we have to decide if this is expected behavior or an error. If it is an error we should propagate it. If it is expected behavior then we should not log it.

2023-11-06 15:51 UTC, oridag commented
@adamgfraser IMO, in the context of checking the health of a connection, errors are expected and should be ignored

2023-11-06 15:52 UTC, adamgfraser commented
@oridag Okay. Then let's go back to your original version and get this merged.

2023-11-06 15:55 UTC, adamgfraser approved these changes

2023-11-06 16:45 UTC, merged