Remove unnecessary parentheses from `JdbcDecoder` and `JdbcDecoder` summoners
zio/zio-jdbc pull request #162
Opened 2023-10-24 13:25 UTC by guizmaii

2023-10-24 14:16 UTC, guizmaii commented on core/src/main/scala/zio/jdbc/JdbcEncoder.scala
> -  def apply[A]()(implicit encoder: JdbcEncoder[A]): JdbcEncoder[A] = encoder
There's no need for these `()` here

2023-10-24 14:16 UTC, guizmaii commented on core/src/test/scala/zio/jdbc/TestConnection.scala
> -  override def unwrap[T <: Object](iface: Class[T]) = ???
It was not compiling in Scala 2.12 with this `<: Object`

2023-10-25 15:26 UTC, adamgfraser requested changes
There are a lot of extraneous changes here. Can we focus on just the specific issue?

2023-10-25 16:43 UTC, guizmaii commented
Superseded by https://github.com/zio/zio-jdbc/pull/167

2023-10-25 16:43 UTC, closed without merging